baseURL: https://nodejh.github.io/hugo-theme-mini
languageCode: en-us
title: Hugo
theme: hugo-theme-mini
pagination:
  pagerSize: 3

# !!! exampleSite only, you may need to delete the line: `themesDir: ../../` 
themesDir: ../../

math: false

hasCJKLanguage: true
permalinks:
  posts: /posts/:title/

googleAnalytics: UA-123-45
disqusShortname: nodejh

showToc: true

markup:
  highlight:
    guessSyntax: true
    style: emacs

social:
  github: https://github.com/adrianbiro
  #twitter: https://twitter.com/nodejh
  #stackoverflow: https://stackoverflow.com/users/4518882/nodejh

params:
  author: nodejh
  bio: Software Engineer
  description: My Blog
  enableRSS: false
  enableComments: true
  socialIcons:
  - name: "rss"
